import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import { IsInt } from "class-validator";

export class CreateListsDto {
       
        @ApiProperty()
        projectId: number;

        // @ApiProperty()
        // listId: number;// generated by the db

        @ApiProperty()
        listName: string;





}