import { ApiProperty } from "@nestjs/swagger";

export class CreateListsDto {
        @ApiProperty()
        projectId: number;

        // @ApiProperty()
        // listId: number;// generated by the db

        @ApiProperty()
        listName: string;





}